export interface Campaign {
  id: number
  name: string
  template: string
  category: string
  status: string
  recipient: number
  delivered: number
  // Detail-only fields
  audience: string
  audienceSuffix?: string
  audienceSub: string
  integration: string
  createdBy: string
  createdAt: string
  createdAtSub: string
  stats: {
    read: number
    delivered: number
    sent: number
    pending: number
    failed: number
  }
}

export const campaigns: Campaign[] = [
  {
    id: 1,
    name: 'promo akhir tahun',
    template: 'promo_akhir_tahun',
    category: 'Marketing',
    status: 'Completed',
    recipient: 24256,
    delivered: 22120,
    audience: 'Dormant customers',
    audienceSuffix: ' (segments)',
    audienceSub: '850 customers listed when the campaign is created.',
    integration: 'Central Perk Indonesia',
    createdBy: 'Christin Purnama Sari (christin@centralperk.id)',
    createdAt: '5 Nov 2025 at 08:30',
    createdAtSub: 'device timezone',
    stats: { read: 2518, delivered: 10028, sent: 1272, pending: 837, failed: 0 },
  },
  {
    id: 2,
    name: 'corporate nitiative',
    template: 'corporate_initiative',
    category: 'Marketing',
    status: 'In progress',
    recipient: 5559,
    delivered: 5800,
    audience: 'Most valuable customers',
    audienceSub: '12.345 customers in WhatsApp',
    integration: 'Central Perk Support',
    createdBy: 'Rizal Candra (rizal@centralperk.id)',
    createdAt: '3 Nov 2025 at 09:00',
    createdAtSub: 'device timezone',
    stats: { read: 5800, delivered: 4900, sent: 600, pending: 59, failed: 0 },
  },
  {
    id: 3,
    name: 'corporate nitiative',
    template: 'influencer_instagram',
    category: 'Marketing',
    status: 'Partially completed',
    recipient: 2228,
    delivered: 4400,
    audience: 'Least purchase customers',
    audienceSub: '19.876 customers in WhatsApp',
    integration: 'Central Perk Indonesia',
    createdBy: 'Rizal Candra (rizal@centralperk.id)',
    createdAt: '1 Nov 2025 at 10:00',
    createdAtSub: 'device timezone',
    stats: { read: 4400, delivered: 3200, sent: 900, pending: 100, failed: 28 },
  },
  {
    id: 4,
    name: 'influencer nstagram',
    template: 'knowledge_exchange',
    category: 'Marketing',
    status: 'Stopped - WhatsApp',
    recipient: 7545,
    delivered: 1300,
    audience: 'Inactive customers',
    audienceSub: '15.678 customers in WhatsApp',
    integration: 'Central Perk Indonesia',
    createdBy: 'Christin Purnama Sari (christin@centralperk.id)',
    createdAt: '28 Oct 2025 at 08:00',
    createdAtSub: 'device timezone',
    stats: { read: 1300, delivered: 1100, sent: 150, pending: 45, failed: 5950 },
  },
  {
    id: 5,
    name: 'knowledge exchange',
    template: 'clearance_event',
    category: 'Marketing',
    status: 'Insufficient balance',
    recipient: 4688,
    delivered: 7300,
    audience: 'Latest abandoned cart',
    audienceSub: '7.890 customers in WhatsApp',
    integration: 'Central Perk Support',
    createdBy: 'Christin Purnama Sari (christin@centralperk.id)',
    createdAt: '25 Oct 2025 at 14:00',
    createdAtSub: 'device timezone',
    stats: { read: 7300, delivered: 6500, sent: 500, pending: 200, failed: 188 },
  },
  {
    id: 6,
    name: 'clearance event',
    template: 'industry_advancement',
    category: 'Marketing',
    status: 'Failed',
    recipient: 3697,
    delivered: 9200,
    audience: 'Recently purchase customers',
    audienceSub: '22.222 customers in WhatsApp',
    integration: 'Central Perk Indonesia',
    createdBy: 'Rizal Candra (rizal@centralperk.id)',
    createdAt: '20 Oct 2025 at 11:00',
    createdAtSub: 'device timezone',
    stats: { read: 0, delivered: 0, sent: 0, pending: 0, failed: 3697 },
  },
  {
    id: 7,
    name: 'industry advancement',
    template: 'global_conference',
    category: 'Marketing',
    status: 'Canceled',
    recipient: 2473,
    delivered: 8800,
    audience: 'Give away ramadhan 2024',
    audienceSub: '3.141 customers in WhatsApp',
    integration: 'Central Perk Support',
    createdBy: 'Christin Purnama Sari (christin@centralperk.id)',
    createdAt: '15 Oct 2025 at 09:30',
    createdAtSub: 'device timezone',
    stats: { read: 0, delivered: 0, sent: 0, pending: 0, failed: 0 },
  },
  {
    id: 8,
    name: 'global conference',
    template: 'limited_time_offer',
    category: 'Utility',
    status: 'Completed',
    recipient: 1005,
    delivered: 8100,
    audience: 'Most valuable customers',
    audienceSub: '12.345 customers in WhatsApp',
    integration: 'Central Perk Indonesia',
    createdBy: 'Rizal Candra (rizal@centralperk.id)',
    createdAt: '10 Oct 2025 at 08:00',
    createdAtSub: 'device timezone',
    stats: { read: 8100, delivered: 7500, sent: 400, pending: 0, failed: 200 },
  },
  {
    id: 9,
    name: 'limited time_offer',
    template: 'loyalty_rewards',
    category: 'Auth',
    status: 'Completed',
    recipient: 4297,
    delivered: 4200,
    audience: 'Least purchase customers',
    audienceSub: '19.876 customers in WhatsApp',
    integration: 'Central Perk Support',
    createdBy: 'Christin Purnama Sari (christin@centralperk.id)',
    createdAt: '5 Oct 2025 at 10:00',
    createdAtSub: 'device timezone',
    stats: { read: 4200, delivered: 4100, sent: 80, pending: 0, failed: 17 },
  },
  {
    id: 10,
    name: 'loyalty rewards',
    template: 'professional_development',
    category: 'Marketing',
    status: 'Completed',
    recipient: 7873,
    delivered: 4200,
    audience: 'Inactive customers',
    audienceSub: '15.678 customers in WhatsApp',
    integration: 'Central Perk Indonesia',
    createdBy: 'Rizal Candra (rizal@centralperk.id)',
    createdAt: '1 Oct 2025 at 08:00',
    createdAtSub: 'device timezone',
    stats: { read: 4200, delivered: 3900, sent: 200, pending: 0, failed: 73 },
  },
  {
    id: 11,
    name: 'flash sale november',
    template: 'flash_sale_nov',
    category: 'Marketing',
    status: 'Scheduled',
    recipient: 3100,
    delivered: 0,
    audience: 'Dormant customers',
    audienceSuffix: ' (segments)',
    audienceSub: '1.050 customers listed when the campaign is created.',
    integration: 'Central Perk Indonesia',
    createdBy: 'Christin Purnama Sari (christin@centralperk.id)',
    createdAt: '28 Sep 2025 at 08:00',
    createdAtSub: 'device timezone',
    stats: { read: 0, delivered: 0, sent: 0, pending: 0, failed: 0 },
  },
  {
    id: 12,
    name: 'year end promo',
    template: 'year_end_promo',
    category: 'Utility',
    status: 'In progress',
    recipient: 1500,
    delivered: 600,
    audience: 'Recently purchase customers',
    audienceSub: '22.222 customers in WhatsApp',
    integration: 'Central Perk Support',
    createdBy: 'Rizal Candra (rizal@centralperk.id)',
    createdAt: '20 Sep 2025 at 09:00',
    createdAtSub: 'device timezone',
    stats: { read: 600, delivered: 520, sent: 60, pending: 20, failed: 0 },
  },
  {
    id: 13,
    name: 'customer survey',
    template: 'customer_survey',
    category: 'Marketing',
    status: 'Completed',
    recipient: 2000,
    delivered: 1900,
    audience: 'Most valuable customers',
    audienceSub: '12.345 customers in WhatsApp',
    integration: 'Central Perk Indonesia',
    createdBy: 'Christin Purnama Sari (christin@centralperk.id)',
    createdAt: '15 Sep 2025 at 08:00',
    createdAtSub: 'device timezone',
    stats: { read: 1900, delivered: 1850, sent: 40, pending: 0, failed: 10 },
  },
  {
    id: 14,
    name: 'product launch',
    template: 'product_launch',
    category: 'Marketing',
    status: 'Failed',
    recipient: 800,
    delivered: 0,
    audience: 'Least purchase customers',
    audienceSub: '19.876 customers in WhatsApp',
    integration: 'Central Perk Support',
    createdBy: 'Rizal Candra (rizal@centralperk.id)',
    createdAt: '10 Sep 2025 at 10:00',
    createdAtSub: 'device timezone',
    stats: { read: 0, delivered: 0, sent: 0, pending: 0, failed: 800 },
  },
  {
    id: 15,
    name: 'otp verification',
    template: 'otp_verify',
    category: 'Auth',
    status: 'Completed',
    recipient: 12000,
    delivered: 11900,
    audience: 'Give away ramadhan 2024',
    audienceSub: '3.141 customers in WhatsApp',
    integration: 'Central Perk Indonesia',
    createdBy: 'Christin Purnama Sari (christin@centralperk.id)',
    createdAt: '5 Sep 2025 at 08:00',
    createdAtSub: 'device timezone',
    stats: { read: 11900, delivered: 11800, sent: 80, pending: 0, failed: 20 },
  },
]

export function useCampaigns() {
  function findById(id: number | string): Campaign | undefined {
    return campaigns.find(c => c.id === Number(id))
  }
  return { campaigns, findById }
}
